### ISSUE TITLE
stimulus 3 supports?

### ISSUE THREAD

**Issue by buncis** [excid3/stimulus-slimselect#15]
its have error `Uncaught Error: Cannot find module 'stimulus'` since the package name changed to `@hotwire/stimulus`

**Comment by arkadiyayvazyan** [comment]
I have the same issue. 
I am using esbuild instead of webpack.

**Comment by buncis** [comment]
I think its better to import the library by ourselves

this library itself is pretty much just doing that 
https://github.com/excid3/stimulus-slimselect/blob/master/src/index.js

**Comment by BenCh94** [comment]
@buncis How did you load the style-sheets for slim-select?, I'm getting "module build failed" error trying to import the CSS.

**Comment by BenCh94** [comment]
> @buncis How did you load the style-sheets for slim-select?, I'm getting "module build failed" error trying to import the CSS.

Actually got this working with the full path to the css:
`@import "node_modules/slim-select/dist/slimselect.min";`

**Comment by phylor** [comment]
Summarised from above.

```shell
bin/rails g stimulus slim_select
```

Replace the controller with:

```js
import { Controller } from "@hotwired/stimulus";
import SlimSelect from "slim-select";

// Connects to data-controller="slim-select"
export default class extends Controller {
  static values = {
    options: Object,
  };

  connect() {
    this.slimselect = new SlimSelect({
      select: this.element,
      ...this.optionsValue,
    });
  }

  disconnect() {
    this.slimselect.destroy();
  }
}
```

In `controllers/application.js` or somewhere else:

```js
import "@node_modules/slim-select/dist/slimselect.min";
```

**Comment by excid3** [comment]
Just released a new version with `@hotwired/stimulus`
